Add files via upload
peotr26/new_super_bolcheland pull request #2
Opened 2023-10-05 07:56 UTC by D-Maxwell

2023-10-05 18:58 UTC, JeanChipo commented
I specify that my 2 suggestions can be subject to change.

2023-10-05 19:35 UTC, peotr26 requested changes
I propose that we keep @JeanChipo second proposition.

2023-10-06 12:16 UTC, D-Maxwell commented
Sure, that second one could be improved once I slightly tweak the "New" particle. Seems like I forgot to slant the text, woops

Besides, we would gain in keeping both logos ready for use, with each one dedicated to either a text or a visual representation of the project ; to that end, I reckon @JeanChipo's participation would fulfil the latter role, whilst mine would fit the former.

TL;DR : Let us keep two logos, mine and the second variant from @JeanChipo, for different uses.

2023-10-06 12:25 UTC, peotr26 approved these changes

2023-10-06 12:25 UTC, merged